spring:
    jpa:
        show-sql: true
        properties:
            hibernate:
                ddl-auto: none
                format-sql: true

product:
    url-find-by-id: http://challenge-api.luizalabs.com/api/product/{id}/